d /etc/palworld-manager 0750 root palmanager -
d /run/palworld-manager 0750 root palmanager -
d /run/palworld-manager/host-control 0770 root palmanager -
d /var/lib/palworld-manager 0750 palmanager palmanager -
d /var/lib/palworld-manager/backups 0750 palmanager palmanager -
d /var/lib/palworld-manager/jobs 0750 palmanager palmanager -
d /var/lib/palworld-manager/deploy 0750 root palmanager -
d /var/lib/palworld-manager/rclone 0700 palmanager palmanager -
d /var/lib/palworld-manager/tmp 0700 palmanager palmanager -
d /var/lib/palworld-manager/tmp/backups 0700 palmanager palmanager -
d /var/lib/palworld-manager/tmp/drive 0700 palmanager palmanager -
d /var/lib/palworld-manager/tmp/restores 0700 palmanager palmanager -
