from dataclasses import dataclass
from decimal import Decimal
from enum import StrEnum

PALWORLD_SETTINGS_SCHEMA_VERSION = "1.0.4"
PALWORLD_SETTINGS_SCHEMA_SOURCE = (
    "https://docs.palworldgame.com/settings-and-operation/configuration/"
)


class SettingKind(StrEnum):
    BOOLEAN = "boolean"
    ENUM = "enum"
    INTEGER = "integer"
    NUMBER = "number"
    READ_ONLY = "read_only"
    SENSITIVE = "sensitive"
    STRING = "string"


@dataclass(frozen=True, slots=True)
class SettingDefinition:
    key: str
    label: str
    description: str
    category: str
    kind: SettingKind
    options: tuple[str, ...] = ()
    minimum: Decimal | None = None
    maximum: Decimal | None = None


def _definition(
    key: str,
    label: str,
    description: str,
    category: str,
    kind: SettingKind,
    *,
    options: tuple[str, ...] = (),
    minimum: int | str | None = None,
    maximum: int | str | None = None,
) -> SettingDefinition:
    return SettingDefinition(
        key=key,
        label=label,
        description=description,
        category=category,
        kind=kind,
        options=options,
        minimum=Decimal(str(minimum)) if minimum is not None else None,
        maximum=Decimal(str(maximum)) if maximum is not None else None,
    )


PERFORMANCE = "Desempenho"
MANAGEMENT = "Administração do servidor"
FEATURES = "Recursos"
BALANCE = "Balanceamento"

SETTING_DEFINITIONS = (
    _definition(
        "BaseCampMaxNum",
        "Total de bases",
        "Quantidade total de bases no servidor.",
        PERFORMANCE,
        SettingKind.INTEGER,
    ),
    _definition(
        "BaseCampMaxNumInGuild",
        "Bases por guilda",
        "Quantidade máxima de bases por guilda.",
        PERFORMANCE,
        SettingKind.INTEGER,
        maximum=10,
    ),
    _definition(
        "BaseCampWorkerMaxNum",
        "Pals por base",
        "Quantidade máxima de Pals trabalhando em cada base.",
        PERFORMANCE,
        SettingKind.INTEGER,
        maximum=50,
    ),
    _definition(
        "ItemContainerForceMarkDirtyInterval",
        "Intervalo de sincronização de contêineres",
        "Frequência, em segundos, para forçar a sincronização de contêineres abertos.",
        PERFORMANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "MaxBuildingLimitNum",
        "Construções por jogador",
        "Limite de construções por jogador; zero significa ilimitado.",
        PERFORMANCE,
        SettingKind.INTEGER,
    ),
    _definition(
        "PhysicsActiveDropItemMaxNum",
        "Itens com física",
        "Quantidade máxima de itens largados que usam física.",
        PERFORMANCE,
        SettingKind.INTEGER,
    ),
    _definition(
        "ServerReplicatePawnCullDistance",
        "Distância de sincronização",
        "Distância de sincronização dos Pals em centímetros.",
        PERFORMANCE,
        SettingKind.NUMBER,
        minimum=5000,
        maximum=15000,
    ),
    _definition(
        "bAllowClientMod",
        "Permitir clientes com mods",
        "Permite a entrada de jogadores com mods habilitados.",
        MANAGEMENT,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "AllowConnectPlatform",
        "Plataforma permitida legada",
        "Parâmetro indisponível nesta versão; use Plataformas crossplay.",
        MANAGEMENT,
        SettingKind.READ_ONLY,
    ),
    _definition(
        "bEnableBuildingPlayerUIdDisplay",
        "Exibir criador das construções",
        "Exibe o identificador do jogador que criou cada estrutura.",
        MANAGEMENT,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bIsShowJoinLeftMessage",
        "Mensagens de entrada e saída",
        "Exibe mensagens quando jogadores entram ou saem.",
        MANAGEMENT,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bIsUseBackupSaveData",
        "Backups internos do Palworld",
        "Habilita os backups internos do mundo feitos pelo Palworld.",
        MANAGEMENT,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "ChatPostLimitPerMinute",
        "Mensagens de chat por minuto",
        "Limite de mensagens de chat por minuto.",
        MANAGEMENT,
        SettingKind.INTEGER,
    ),
    _definition(
        "LogFormatType",
        "Formato dos logs",
        "Formato emitido pelo servidor.",
        MANAGEMENT,
        SettingKind.ENUM,
        options=("Text", "Json"),
    ),
    _definition(
        "PublicIP",
        "IP público",
        "IP externo anunciado pelo servidor comunitário.",
        MANAGEMENT,
        SettingKind.STRING,
    ),
    _definition(
        "PublicPort",
        "Porta pública",
        "Porta externa anunciada pelo servidor comunitário.",
        MANAGEMENT,
        SettingKind.INTEGER,
        minimum=1,
        maximum=65535,
    ),
    _definition(
        "RCONEnabled",
        "Habilitar RCON",
        "Habilita o protocolo RCON.",
        MANAGEMENT,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "RCONPort",
        "Porta RCON",
        "Porta usada pelo RCON.",
        MANAGEMENT,
        SettingKind.INTEGER,
        minimum=1,
        maximum=65535,
    ),
    _definition(
        "RESTAPIEnabled",
        "Habilitar REST API",
        "Habilita a REST API oficial usada pelo Manager.",
        MANAGEMENT,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "RESTAPIPort",
        "Porta da REST API",
        "Porta de escuta da REST API oficial.",
        MANAGEMENT,
        SettingKind.INTEGER,
        minimum=1,
        maximum=65535,
    ),
    _definition(
        "ServerDescription",
        "Descrição do servidor",
        "Descrição apresentada pelo servidor.",
        MANAGEMENT,
        SettingKind.STRING,
    ),
    _definition(
        "ServerName",
        "Nome do servidor",
        "Nome apresentado pelo servidor.",
        MANAGEMENT,
        SettingKind.STRING,
    ),
    _definition(
        "ServerPlayerMaxNum",
        "Máximo de jogadores",
        "Quantidade máxima de jogadores conectados.",
        MANAGEMENT,
        SettingKind.INTEGER,
    ),
    _definition(
        "AdminPassword",
        "Senha administrativa",
        "Campo sensível preservado sem exibir seu valor.",
        MANAGEMENT,
        SettingKind.SENSITIVE,
    ),
    _definition(
        "ServerPassword",
        "Senha do servidor",
        "Campo sensível preservado sem exibir seu valor.",
        MANAGEMENT,
        SettingKind.SENSITIVE,
    ),
    _definition(
        "CrossplayPlatforms",
        "Plataformas crossplay",
        "Estrutura composta reconhecida e preservada sem edição nesta versão.",
        MANAGEMENT,
        SettingKind.READ_ONLY,
    ),
    _definition(
        "AutoResetGuildTimeNoOnlinePlayers",
        "Tempo para remover guilda inativa",
        "Tempo sem membros online antes da remoção automática da guilda.",
        FEATURES,
        SettingKind.NUMBER,
    ),
    _definition(
        "bAllowEnemyCampSpawnNearBaseCamp",
        "Permitir acampamentos inimigos próximos",
        "Permite o surgimento de acampamentos inimigos perto das bases dos jogadores.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bAllowEnhanceStat_Attack",
        "Permitir atributo de ataque",
        "Permite distribuir pontos no atributo de ataque.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bAllowEnhanceStat_Health",
        "Permitir atributo de vida",
        "Permite distribuir pontos no atributo de vida.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bAllowEnhanceStat_Stamina",
        "Permitir atributo de stamina",
        "Permite distribuir pontos no atributo de stamina.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bAllowEnhanceStat_Weight",
        "Permitir atributo de peso",
        "Permite distribuir pontos no atributo de capacidade de peso.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bAllowEnhanceStat_WorkSpeed",
        "Permitir atributo de velocidade de trabalho",
        "Permite distribuir pontos no atributo de velocidade de trabalho.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bAllowGlobalPalboxExport",
        "Permitir exportação pelo Palbox global",
        "Permite exportar Pals pelo Palbox global.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bAllowGlobalPalboxImport",
        "Permitir importação pelo Palbox global",
        "Permite importar Pals pelo Palbox global.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bAutoResetGuildNoOnlinePlayers",
        "Remover guildas inativas",
        (
            "Remove estruturas e Pals da base quando nenhum membro entrar "
            "durante o período configurado."
        ),
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bBuildAreaLimit",
        "Restringir áreas de construção",
        "Impede construções perto de locais importantes, como pontos de viagem rápida.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bCanPickupOtherGuildDeathPenaltyDrop",
        "Permitir coleta de perdas de outras guildas",
        "Permite coletar itens e Pals perdidos por jogadores de outras guildas.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bCharacterRecreateInHardcore",
        "Recriar personagem no modo hardcore",
        "Permite recriar o personagem após a morte no modo hardcore.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bDisplayPvPItemNumOnWorldMap_BaseCamp",
        "Exibir itens PvP das bases",
        "Exibe no mapa a quantidade de itens PvP em cada base.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bDisplayPvPItemNumOnWorldMap_Player",
        "Exibir itens PvP dos jogadores",
        "Exibe no mapa a posição e a quantidade de itens PvP dos jogadores.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bEnableAimAssistPad",
        "Habilitar assistência de mira no controle",
        "Habilita a assistência de mira para jogadores que usam controle.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bEnableDefenseOtherGuildPlayer",
        "Defender contra outras guildas",
        "Permite que Pals da base ataquem jogadores hostis de outras guildas.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bEnableFastTravel",
        "Permitir viagem rápida",
        "Habilita a viagem rápida.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bEnableFastTravelOnlyBaseCamp",
        "Restringir viagem rápida às bases",
        "Permite viagem rápida somente entre bases.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bEnableInvaderEnemy",
        "Habilitar invasões",
        "Habilita inimigos invasores.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bEnableVoiceChat",
        "Habilitar chat de voz",
        "Habilita o chat de voz do jogo.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bEnablePlayerToPlayerDamage",
        "Habilitar dano entre jogadores",
        "Permite que jogadores causem dano uns aos outros.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bExistPlayerAfterLogout",
        "Manter jogador após logout",
        "Mantém o jogador dormindo na posição atual depois do logout.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bHardcore",
        "Habilitar modo hardcore",
        "Habilita o modo hardcore, sem renascimento após a morte.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bInvisibleOtherGuildBaseCampAreaFX",
        "Ocultar área das bases de outras guildas",
        "Controla a visibilidade dos limites das bases de outras guildas.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bIsPvP",
        "Habilitar PvP",
        "Habilita o modo PvP.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bIsRandomizerPalLevelRandom",
        "Aleatorizar completamente o nível dos Pals",
        "Aleatoriza completamente os níveis; desativado, respeita a faixa de cada região.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bIsStartLocationSelectByMap",
        "Permitir escolha do local inicial",
        "Permite escolher pelo mapa o local inicial do personagem.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "bShowPlayerList",
        "Exibir lista de jogadores",
        "Exibe a lista de jogadores no menu do jogo.",
        FEATURES,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "RandomizerType",
        "Modo de aleatorização",
        "Modo de aleatorização do surgimento de Pals.",
        FEATURES,
        SettingKind.ENUM,
        options=("None", "Region", "All"),
    ),
    _definition(
        "RandomizerSeed",
        "Seed da aleatorização",
        "Seed usada pelo modo de aleatorização.",
        FEATURES,
        SettingKind.INTEGER,
    ),
    _definition(
        "VoiceChatMaxVolumeDistance",
        "Distância máxima do chat de voz",
        "Distância até a qual o volume do chat de voz não é atenuado.",
        FEATURES,
        SettingKind.NUMBER,
    ),
    _definition(
        "VoiceChatZeroVolumeDistance",
        "Distância sem volume do chat de voz",
        "Distância na qual o volume do chat de voz chega a zero.",
        FEATURES,
        SettingKind.NUMBER,
    ),
    _definition(
        "AdditionalDropItemNumWhenPlayerKillingInPvPMode",
        "Quantidade da recompensa PvP",
        "Quantidade do item derrubado ao eliminar um jogador no modo PvP.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "AdditionalDropItemWhenPlayerKillingInPvPMode",
        "Item de recompensa PvP",
        "Estrutura composta reconhecida e preservada sem edição nesta versão.",
        BALANCE,
        SettingKind.READ_ONLY,
    ),
    _definition(
        "bAdditionalDropItemWhenPlayerKillingInPvPMode",
        "Habilitar recompensa por eliminação PvP",
        "Derruba um item especial ao eliminar um jogador no modo PvP.",
        BALANCE,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "BlockRespawnTime",
        "Tempo para renascer",
        "Tempo de espera, em segundos, antes de renascer após a morte.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "bPalLost",
        "Perder Pals permanentemente",
        "Remove permanentemente os Pals perdidos após a morte.",
        BALANCE,
        SettingKind.BOOLEAN,
    ),
    _definition(
        "BuildObjectDamageRate",
        "Dano contra construções",
        "Multiplicador do dano causado a construções.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "BuildObjectDeteriorationDamageRate",
        "Deterioração de construções",
        "Multiplicador da velocidade de deterioração das construções.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "CollectionDropRate",
        "Quantidade de itens coletados",
        "Multiplicador da quantidade de itens obtidos na coleta.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "CollectionObjectHpRate",
        "Vida dos objetos coletáveis",
        "Multiplicador da vida dos objetos coletáveis.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "CollectionObjectRespawnSpeedRate",
        "Renascimento dos objetos coletáveis",
        "Multiplicador do intervalo de renascimento dos objetos coletáveis.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "DayTimeSpeedRate",
        "Velocidade do dia",
        "Multiplicador da passagem do tempo durante o dia.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "NightTimeSpeedRate",
        "Velocidade da noite",
        "Multiplicador da passagem do tempo durante a noite.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "ExpRate",
        "Experiência",
        "Multiplicador de experiência recebida.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PalCaptureRate",
        "Captura de Pals",
        "Multiplicador da chance de captura.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PalSpawnNumRate",
        "Surgimento de Pals",
        "Multiplicador da quantidade de Pals; pode afetar o desempenho.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PalDamageRateAttack",
        "Dano causado por Pals",
        "Multiplicador do dano causado por Pals.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PalDamageRateDefense",
        "Dano recebido por Pals",
        "Multiplicador do dano recebido por Pals.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PlayerDamageRateAttack",
        "Dano causado por jogadores",
        "Multiplicador do dano causado por jogadores.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PlayerDamageRateDefense",
        "Dano recebido por jogadores",
        "Multiplicador do dano recebido por jogadores.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PalEggDefaultHatchingTime",
        "Tempo de incubação",
        "Horas para incubar um ovo enorme.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "GuildPlayerMaxNum",
        "Jogadores por guilda",
        "Quantidade máxima de jogadores em uma guilda.",
        BALANCE,
        SettingKind.INTEGER,
    ),
    _definition(
        "SupplyDropSpan",
        "Intervalo de suprimentos",
        "Intervalo em minutos para meteoritos e suprimentos.",
        BALANCE,
        SettingKind.INTEGER,
    ),
    _definition(
        "DeathPenalty",
        "Penalidade por morte",
        "Itens e Pals perdidos após a morte.",
        BALANCE,
        SettingKind.ENUM,
        options=("None", "Item", "ItemAndEquipment", "All"),
    ),
    _definition(
        "DenyTechnologyList",
        "Tecnologias bloqueadas",
        "Lista composta reconhecida e preservada sem edição nesta versão.",
        BALANCE,
        SettingKind.READ_ONLY,
    ),
    _definition(
        "EnemyDropItemRate",
        "Itens derrubados por inimigos",
        "Multiplicador da quantidade de itens derrubados por inimigos.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "EquipmentDurabilityDamageRate",
        "Perda de durabilidade",
        "Multiplicador da perda de durabilidade dos equipamentos.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "FishingDifficultyRate",
        "Dificuldade da pesca",
        "Multiplicador da dificuldade da pesca.",
        BALANCE,
        SettingKind.NUMBER,
        minimum="0.1",
        maximum="1.0",
    ),
    _definition(
        "GuildRejoinCooldownMinutes",
        "Espera para retornar à guilda",
        "Tempo de espera, em minutos, para retornar a uma guilda.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "ItemCorruptionMultiplier",
        "Deterioração dos itens",
        "Multiplicador da velocidade de deterioração dos itens.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "ItemWeightRate",
        "Peso dos itens",
        "Multiplicador do peso dos itens.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "MonsterFarmActionSpeedRate",
        "Produção no rancho",
        "Multiplicador da velocidade de produção de itens no rancho.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PalAutoHPRegeneRate",
        "Regeneração natural dos Pals",
        "Multiplicador da regeneração natural de vida dos Pals.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PalAutoHpRegeneRateInSleep",
        "Regeneração dos Pals no Palbox",
        "Multiplicador da regeneração de vida dos Pals enquanto descansam no Palbox.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PalStaminaDecreaceRate",
        "Consumo de stamina dos Pals",
        "Multiplicador do consumo de stamina dos Pals.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PalStomachDecreaceRate",
        "Fome dos Pals",
        "Multiplicador do consumo de alimento dos Pals.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PlayerAutoHPRegeneRate",
        "Regeneração natural dos jogadores",
        "Multiplicador da regeneração natural de vida dos jogadores.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PlayerAutoHpRegeneRateInSleep",
        "Regeneração dos jogadores dormindo",
        "Multiplicador da regeneração de vida dos jogadores enquanto dormem.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PlayerStaminaDecreaceRate",
        "Consumo de stamina dos jogadores",
        "Multiplicador do consumo de stamina dos jogadores.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "PlayerStomachDecreaceRate",
        "Fome dos jogadores",
        "Multiplicador do consumo de alimento dos jogadores.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "RespawnPenaltyDurationThreshold",
        "Limite da penalidade de renascimento",
        "Tempo de sobrevivência, em segundos, para reiniciar a penalidade de renascimento.",
        BALANCE,
        SettingKind.NUMBER,
    ),
    _definition(
        "RespawnPenaltyTimeScale",
        "Escala da penalidade de renascimento",
        "Multiplicador aplicado ao tempo de espera para renascer.",
        BALANCE,
        SettingKind.NUMBER,
    ),
)

SETTING_DEFINITIONS_BY_KEY = {definition.key: definition for definition in SETTING_DEFINITIONS}
SETTING_CATEGORIES = (PERFORMANCE, MANAGEMENT, FEATURES, BALANCE)
