"""create initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-13 18:50:58.721131
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("progress", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_cancellable", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "requires_maintenance_lock", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("claimed_by", sa.String(length=100), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("log_path", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name=op.f("ck_jobs_progress_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)

    op.create_table(
        "users",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_app_settings_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_settings")),
    )
    op.create_table(
        "audit_events",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("origin", sa.String(length=30), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("target", sa.String(length=255), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_audit_events_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_events_origin"), ["origin"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_result"), ["result"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "backup_records",
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_backup_records_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backup_records")),
        sa.UniqueConstraint("filename", name=op.f("uq_backup_records_filename")),
    )
    with op.batch_alter_table("backup_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_backup_records_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_backup_records_location"), ["location"], unique=False)
        batch_op.create_index(batch_op.f("ix_backup_records_status"), ["status"], unique=False)

    op.create_table(
        "ban_history",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("palworld_user_id", sa.String(length=255), nullable=False),
        sa.Column("target_name", sa.String(length=255), nullable=True),
        sa.Column("administrator_user_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["administrator_user_id"],
            ["users.id"],
            name=op.f("fk_ban_history_administrator_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ban_history")),
    )
    with op.batch_alter_table("ban_history", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ban_history_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ban_history_administrator_user_id"),
            ["administrator_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_ban_history_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ban_history_palworld_user_id"), ["palworld_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ban_history_result"), ["result"], unique=False)

    op.create_table(
        "login_attempts",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("source_address", sa.String(length=45), nullable=True),
        sa.Column("successful", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("blocked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_login_attempts_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempts")),
    )
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_login_attempts_attempted_at"), ["attempted_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_login_attempts_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_login_attempts_username"), ["username"], unique=False)

    op.create_table(
        "notification_events",
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("channel", sa.String(length=30), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'SENDING', 'SENT', 'FAILED')",
            name=op.f("ck_notification_events_valid_status"),
        ),
        sa.CheckConstraint(
            "attempts >= 0 AND attempts <= 3", name=op.f("ck_notification_events_attempts_range")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_notification_events_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_events")),
    )
    with op.batch_alter_table("notification_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_events_channel"), ["channel"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notification_events_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notification_events_next_attempt_at"), ["next_attempt_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notification_events_status"), ["status"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_expires_at"))

    op.drop_table("sessions")
    with op.batch_alter_table("notification_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_events_status"))
        batch_op.drop_index(batch_op.f("ix_notification_events_next_attempt_at"))
        batch_op.drop_index(batch_op.f("ix_notification_events_job_id"))
        batch_op.drop_index(batch_op.f("ix_notification_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_notification_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_notification_events_channel"))

    op.drop_table("notification_events")
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_attempts_username"))
        batch_op.drop_index(batch_op.f("ix_login_attempts_user_id"))
        batch_op.drop_index(batch_op.f("ix_login_attempts_attempted_at"))

    op.drop_table("login_attempts")
    with op.batch_alter_table("ban_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ban_history_result"))
        batch_op.drop_index(batch_op.f("ix_ban_history_palworld_user_id"))
        batch_op.drop_index(batch_op.f("ix_ban_history_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_ban_history_administrator_user_id"))
        batch_op.drop_index(batch_op.f("ix_ban_history_action"))

    op.drop_table("ban_history")
    with op.batch_alter_table("backup_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_backup_records_status"))
        batch_op.drop_index(batch_op.f("ix_backup_records_location"))
        batch_op.drop_index(batch_op.f("ix_backup_records_job_id"))

    op.drop_table("backup_records")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_result"))
        batch_op.drop_index(batch_op.f("ix_audit_events_origin"))
        batch_op.drop_index(batch_op.f("ix_audit_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_audit_events_job_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_action"))

    op.drop_table("audit_events")
    op.drop_table("app_settings")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_kind"))

    op.drop_table("jobs")
    # ### end Alembic commands ###
